# /home/tis/websites/[ENV]/hosting-core/docker-compose.yml

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: ${ENV_NAME}_cloudflared
    restart: always
    
    env_file:
      - ../.env
  
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      
    command: tunnel run
    
    networks:
      - tis_proxy

networks:
  tis_proxy:
    name: ${NETWORK_NAME}
    driver: bridge
